name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.0"
          php_extensions: bcmath json pdo
      - name: Directory Permissions
        run: chmod -R 777 storage vendor/orchestra/testbench-core/laravel/bootstrap/cache
      - name: Create Database
        run: |
          touch tests/testbase.sqlite
      - name: Run tests
        run: vendor/bin/phpunit --stop-on-failure
